// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace GigHub.Persistance.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddisCanceledToGig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddisCanceledToGig));
        
        string IMigrationMetadata.Id
        {
            get { return "201807261334568_AddisCanceledToGig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
